title: My New GitHub Pages Blog
author: @crwgrant
description: > # this means to ignore newlines until "baseurl:"
  Practice creating a GitHub pages website

# social links
twitter_username: @crwgrant
github_username:  @crwgrant

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
